server.port: 17000

app:
  product-service:
    host: localhost
    port: 17001
  recommendation-service:
    host: localhost
    port: 17002
  review-service:
    host: localhost
    port: 17003

logging:
  level:
    root: INFO
    jp.vmware.sol: DEBUG
